apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    release: statefulsetplus
  name: statefulsetpluses.tkex.tencent.com
spec:
  group: tkex.tencent.com
  names:
    kind: StatefulSetPlus
    listKind: StatefulSetPlusList
    plural: statefulsetpluses
    singular: statefulsetplus
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
    scale:
      specReplicasPath: .spec.replicas
      statusReplicasPath: .status.replicas
      labelSelectorPath: .status.labelSelector