# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

required = [
  "github.com/aws/aws-sdk-go",
  "github.com/gophercloud/gophercloud",
  "golang.org/x/oauth2",
  "github.com/openzipkin/zipkin-go-opentracing",
  "github.com/jmespath/go-jmespath",
  "cloud.google.com/go/compute/metadata",
  "github.com/rcrowley/go-metrics",
  "github.com/emicklei/go-restful",
  "github.com/onsi/ginkgo", # for test framework
  "github.com/onsi/gomega", # for test matchers
  "k8s.io/client-go/plugin/pkg/client/auth/gcp", # for development against gcp
  "k8s.io/code-generator/cmd/client-gen", # for go generate
  "k8s.io/code-generator/cmd/deepcopy-gen", # for go generate
  "k8s.io/code-generator/cmd/lister-gen", # for go generate
  "k8s.io/code-generator/cmd/informer-gen", # for go generate
  "sigs.k8s.io/controller-tools/cmd/controller-gen", # for crd/rbac generation
  "sigs.k8s.io/controller-runtime/pkg/client/config",
  "sigs.k8s.io/controller-runtime/pkg/controller",
  "sigs.k8s.io/controller-runtime/pkg/handler",
  "sigs.k8s.io/controller-runtime/pkg/manager",
  "sigs.k8s.io/controller-runtime/pkg/runtime/signals",
  "sigs.k8s.io/controller-runtime/pkg/source",
  "sigs.k8s.io/testing_frameworks/integration", # for integration testing
  "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1",
  "github.com/haproxytech/models",
  "github.com/haproxytech/client-native/runtime",
  "github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common",
  "github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/clb/v20180317",
  "github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/vpc/v20170312",
  "github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cvm/v20170312",
  "github.com/containernetworking/plugins/plugins/main/macvlan",
  "github.com/containernetworking/plugins/plugins/main/bridge",
  "github.com/containernetworking/plugins/plugins/main/ptp",
]

[[override]]
  name = "github.com/DataDog/dd-trace-go"
  version = "1.7.0"

[[constraint]]
  name = "github.com/Microsoft/go-winio"
  version = "0.4.11"

[[constraint]]
  branch = "master"
  name = "github.com/andygrunwald/megos"

[[constraint]]
  name = "github.com/asaskevich/govalidator"
  version = "9.0.0"

[[constraint]]
  name = "github.com/bitly/go-simplejson"
  version = "0.5.0"

[[constraint]]
  name = "github.com/containernetworking/cni"
  version = "0.6.0"

[[constraint]]
  name = "github.com/containernetworking/plugins"
  version = "v0.6.0"

[[override]]
  name = "github.com/coredns/coredns"
  version = "1.3.0"

[[constraint]]
  name = "github.com/coreos/etcd"
  version = "3.3.10"

[[constraint]]
  branch = "master"
  name = "github.com/danwakefield/fnmatch"

[[constraint]]
  branch = "master"
  name = "github.com/dchest/uniuri"

[[constraint]]
  name = "github.com/deckarep/golang-set"
  version = "1.7.1"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  name = "github.com/docker/engine-api"
  version = "0.4.0"

[[constraint]]
  name = "github.com/elastic/beats"
  version = "5.6.14"

[[constraint]]
  name = "github.com/emicklei/go-restful"
  version = "2.8.0"

[[constraint]]
  name = "github.com/fsnotify/fsnotify"
  version = "1.4.7"

[[constraint]]
  name = "github.com/fsouza/go-dockerclient"
  version = "1.3.1"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.4.1"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.1.0"

[[constraint]]
  name = "github.com/google/go-cmp"
  version = "0.2.0"

[[constraint]]
  name = "github.com/google/go-querystring"
  version = "1.0.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.4.0"

[[constraint]]
  branch = "master"
  name = "github.com/iancoleman/strcase"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.9.2"

[[constraint]]
  name = "github.com/json-iterator/go"
  version = "1.1.5" 

[[constraint]]
  name = "github.com/mesos/mesos-go"
  version = "0.0.10"

[[constraint]]
  name = "github.com/mholt/caddy"
  version = "0.11.1"

[[constraint]]
  name = "github.com/miekg/dns"
  version = "1.1.1"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.7.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.4.3"

[[constraint]]
  name = "github.com/parnurzeal/gorequest"
  version = "0.2.15"

[[constraint]]
  name = "github.com/pborman/uuid"
  version = "1.2.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.9.2"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/client_model"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/common"

[[constraint]]
  branch = "master"
  name = "github.com/samuel/go-zookeeper"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.2.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.3.1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  name = "github.com/ugorji/go"
  version = "1.1.1"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  name = "gopkg.in/go-playground/validator.v9"
  version = "9.24.0"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/mgo.v2"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "1.13.1"

[[constraint]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.12.3"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.16.11"

[[constraint]]
  branch = "master"
  name = "github.com/gophercloud/gophercloud"

[[constraint]]
  revision = "c2b33e84"
  name = "github.com/jmespath/go-jmespath"

[[constraint]]
  name = "cloud.google.com/go"
  version = "v0.34.0"

[[constraint]]
  name = "github.com/rcrowley/go-metrics"
  revision = "4b2ddcb0bf13dce7963e46b97826d2695ed2f614"

[[override]]
  name = "github.com/Azure/go-autorest"
  version = "~10.9.0"

[prune]
  go-tests = true
  unused-packages = true

[[prune.project]]
  name = "github.com/coredns/coredns"
  go-tests = false
  unused-packages = false

[[prune.project]]
  name = "github.com/mholt/caddy"
  unused-packages = false

[[prune.project]]
  name = "k8s.io/client-go"
  unused-packages = false

[[prune.project]]
  name = "github.com/aws/aws-sdk-go"
  unused-packages = false

[[prune.project]]
  name = "github.com/DataDog/dd-trace-go"
  go-tests = false
  unused-packages = false

[[prune.project]]
  name = "github.com/gophercloud/gophercloud"
  unused-packages = false

[[prune.project]]
  name = "golang.org/x/oauth2"
  go-tests = false
  unused-packages = false

[[constraint]]
  name = "github.com/google/cadvisor"
  version = "v0.32.0"

[[constraint]]
  name = "github.com/containerd/containerd"
  version = "v1.1.8"

[[constraint]]
  name = "github.com/tencentcloud/tencentcloud-sdk-go"
  version = "v3.0.103"

[[constraint]]
  name = "github.com/haproxytech/models"
  version = "v1.2.4"

[[constraint]]
  name = "github.com/haproxytech/client-native"
  version = "v1.2.6"

[[constraint]]
  name = "github.com/container-storage-interface/spec"
  version = "v0.3.0"

[[constraint]]
  name = "github.com/godbus/dbus"
  version = "v5.0.1"

[[constraint]]
  name = "github.com/coreos/go-systemd"
  version = "v20"


